'use client';
import {useEffect,useMemo,useState} from "react";
import {geoMercator,geoPath,type GeoGeometryObjects} from "d3-geo";
import {AnimatePresence,motion,useReducedMotion} from "framer-motion";
import {ArrowLeft,Search,MapPin} from "lucide-react";
type F={type:"Feature";geometry:GeoGeometryObjects;properties:{adm1_psgc:number;adm1_en:string}};
type C={type:"FeatureCollection";features:F[]};
type P={psgc:number;name:string;region_psgc:number;region_name:string};
type M={psgc:number;name:string;region_psgc:number;region_name:string;province_psgc:number;province_name:string};
type Index={regions:{nir:{psgc:number;name:string}[]};provinces:P[];municities:M[]};
const URL="/Ph/data/country.0.001.json";
const INDEX_URL="/Ph/data/psgc-index.json";
const desc:Record<string,string>={"National Capital Region (NCR)":"The country's metropolitan capital and a center of government, commerce and culture.","Cordillera Administrative Region (CAR)":"A mountainous northern Luzon region known for highland communities and terraces.","Region I (Ilocos Region)":"Northern Luzon, known for heritage towns, coastlines and mountain landscapes.","Region II (Cagayan Valley)":"A wide northern valley framed by the Sierra Madre and Cordillera ranges.","Region III (Central Luzon)":"A broad plain at the heart of Luzon and a major agricultural region.","Region IV-A (CALABARZON)":"A highly connected region south of Metro Manila with cities, industry and countryside.","MIMAROPA Region":"An archipelagic region of islands, reefs, forests and coastal communities.","Region V (Bicol Region)":"The Bicol peninsula and its islands, shaped by volcanoes and the Pacific.","Region VI (Western Visayas)":"Panay, Guimaras and surrounding island communities.","Negros Island Region (NIR)":"Negros and Siquijor, a central island region of diverse communities.","Region VII (Central Visayas)":"A central island corridor anchored by Cebu and Bohol.","Region VIII (Eastern Visayas)":"The eastern seaboard of the Visayas facing the Pacific.","Region IX (Zamboanga Peninsula)":"The western peninsula of Mindanao, rich in coastal and cultural diversity.","Region X (Northern Mindanao)":"Northern Mindanao's highlands, cities and coastal plains.","Region XI (Davao Region)":"Southeastern Mindanao centered around Davao and Mount Apo.","Region XII (SOCCSKSARGEN)":"A diverse south-central Mindanao region of coasts, plains and highlands.","Region XIII (Caraga)":"Northeastern Mindanao, known for forests, rivers and Pacific coastlines.","Bangsamoro Autonomous Region In Muslim Mindanao (BARMM)":"An autonomous region spanning parts of mainland Mindanao and the Sulu archipelago."};
const short=(s:string)=>s.replace(/^Region \w+\s*\((.*)\)$/,"$1").replace(/^Region \w+\s*/,"").trim();
const ease=[0.22,1,0.36,1] as const;
export default function PhilippinesMap(){
 const[data,setData]=useState<C|null>(null),[index,setIndex]=useState<Index|null>(null),[error,setError]=useState(false),[selected,setSelected]=useState<F|null>(null),[q,setQ]=useState(""),[hovered,setHovered]=useState<F|null>(null);
 const reduced=useReducedMotion();
 useEffect(()=>{Promise.all([fetch(URL),fetch(INDEX_URL)]).then(async([mapRes,indexRes])=>{if(!mapRes.ok||!indexRes.ok)throw new Error("Data request failed");return [await mapRes.json(),await indexRes.json()] as const}).then(([mapJson,indexJson])=>{setData(mapJson);setIndex(indexJson)}).catch(()=>setError(true))},[]);
 const fs=data?.features??[],filtered=useMemo(()=>fs.filter(f=>f.properties.adm1_en.toLowerCase().includes(q.toLowerCase())),[fs,q]);
 const projection=useMemo(()=>data?geoMercator().fitExtent([[35,15],[965,565]],data as any):geoMercator(),[data]),path=useMemo(()=>geoPath(projection),[projection]);
 const enter=reduced?{opacity:1}:{opacity:1,y:0};
 return <div className="site">
  <header className="header"><motion.div className="wordmark" initial={{opacity:0,x:-8}} animate={enter} transition={{duration:.45,ease}}>THE PHILIPPINES</motion.div><motion.a className="source" href="https://github.com/tordecilla/ph-drilldown-map" target="_blank" rel="noreferrer" initial={{opacity:0,x:8}} animate={enter} transition={{duration:.45,delay:.08,ease}}>MAP DATA ↗</motion.a></header>
  <section className="visualAtlas" aria-label="Philippine imagery">
   <div className="atlasIntro"><span>VISUAL ATLAS</span><p>Landscapes and places across the Philippine archipelago.</p></div>
   <div className="atlasGrid">
    <figure className="atlasCard atlasWide"><img src="https://commons.wikimedia.org/wiki/Special:FilePath/Amazing_El_Nido.jpg?width=1400" alt="Aerial view of El Nido, Palawan" loading="lazy"/><figcaption><b>Palawan</b><span>El Nido</span></figcaption></figure>
    <figure className="atlasCard"><img src="https://commons.wikimedia.org/wiki/Special:FilePath/Taal_Volcano_aerial_2013.jpg?width=1000" alt="Aerial view of Taal Volcano and its lake" loading="lazy"/><figcaption><b>Luzon</b><span>Taal</span></figcaption></figure>
    <figure className="atlasCard"><img src="https://commons.wikimedia.org/wiki/Special:FilePath/Travel_to_Samal_Island_Philippines.jpg?width=1000" alt="Samal Island in the Philippines" loading="lazy"/><figcaption><b>Mindanao</b><span>Samal Island</span></figcaption></figure>
   </div>
   <div className="atlasCredit">Photography via Wikimedia Commons · <a href="https://commons.wikimedia.org/wiki/Category:Islands_of_the_Philippines" target="_blank" rel="noreferrer">view source collection ↗</a></div>
  </section>
  <motion.section className="hero" initial={{opacity:0,y:reduced?0:18}} animate={{opacity:1,y:0}} transition={{duration:.65,ease}}>
   <motion.div className="eyebrow" initial={{opacity:0,y:8}} animate={enter} transition={{duration:.45,delay:.08,ease}}>An interactive map</motion.div>
   <motion.h1 initial={{opacity:0,y:reduced?0:24}} animate={enter} transition={{duration:.75,delay:.12,ease}}>Explore the Philippines.</motion.h1>
   <motion.p initial={{opacity:0,y:reduced?0:14}} animate={enter} transition={{duration:.55,delay:.22,ease}}>One country, eighteen regions, thousands of places. Select a region to begin your way through the islands.</motion.p>
  </motion.section>
  <section className="mapSection"><div className="mapFrame"><motion.div className="mapMeta" initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.35,duration:.4}}><b>PHILIPPINES</b><motion.span key={hovered?.properties.adm1_psgc??"hint"} initial={{opacity:0,y:4}} animate={{opacity:1,y:0}} transition={{duration:.2}}>{hovered?short(hovered.properties.adm1_en):"Tap or hover a region"}</motion.span></motion.div>
   <div className="mapWrap">
    <motion.div className="search" initial={{opacity:0,y:-8}} animate={{opacity:1,y:0}} transition={{delay:.45,duration:.45,ease}} whileFocus={{boxShadow:"0 14px 36px rgba(23,32,42,.12)"}}><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Find a region…" aria-label="Find a region"/><AnimatePresence>{q&&<motion.div className="searchResults" initial={{opacity:0,y:-5,scale:.99}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:-5}} transition={{duration:.18,ease}}>{filtered.length?filtered.map((f,i)=><motion.button className="result" key={f.properties.adm1_psgc} onClick={()=>{setSelected(f);setQ("")}} initial={{opacity:0,y:4}} animate={{opacity:1,y:0}} transition={{delay:Math.min(i*.025,.12),duration:.2}} whileHover={{x:3}} whileTap={{scale:.99}}>{short(f.properties.adm1_en)}<small>{f.properties.adm1_psgc}</small></motion.button>):<div className="noResult">No region found.</div>}</motion.div>}</AnimatePresence></motion.div>
    <svg className="mapSvg" viewBox="0 0 1000 600" role="img" aria-label="Interactive Philippine regional map">
     {data?fs.map((f,i)=>{const active=selected?.properties.adm1_psgc===f.properties.adm1_psgc,dim=!!selected&&!active;return <motion.path key={f.properties.adm1_psgc} d={path(f as any)||""} className={"regionPath "+(active?"active ":"")+(dim?"dim":"")} initial={{opacity:0}} animate={{opacity:dim?.28:1}} transition={{duration:reduced?.01:.48,delay:reduced?0:Math.min(i*.025,.42),ease}} whileHover={reduced?undefined:{scale:1.006,transition:{duration:.18,ease}}} whileTap={reduced?undefined:{scale:.997}} onMouseEnter={()=>setHovered(f)} onMouseLeave={()=>setHovered(null)} onFocus={()=>setHovered(f)} onBlur={()=>setHovered(null)} onClick={()=>setSelected(f)} onKeyDown={e=>e.key==="Enter"&&setSelected(f)} tabIndex={0} aria-label={short(f.properties.adm1_en)}/>}) : error?<text x="500" y="300" textAnchor="middle" fill="#68717c">Map data could not be loaded.</text>:<text x="500" y="300" textAnchor="middle" fill="#68717c">Loading the map…</text>}
    </svg>
    <AnimatePresence mode="wait" initial={false}>{selected?<motion.aside key="selected" className="panel" initial={{opacity:0,y:18,scale:.985}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:12,scale:.985}} transition={{duration:reduced?.01:.38,ease}}><div className="panelTop"><motion.button className="back" onClick={()=>setSelected(null)} whileHover={{x:-3}} whileTap={{scale:.97}}><ArrowLeft size={14}/> All regions</motion.button><motion.span key={selected.properties.adm1_psgc} initial={{opacity:0}} animate={{opacity:1}}>{selected.properties.adm1_psgc}</motion.span></div><motion.h2 key={selected.properties.adm1_en} initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} transition={{delay:.05,duration:.3,ease}}>{short(selected.properties.adm1_en)}</motion.h2><motion.p initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.1,duration:.3}}>{desc[selected.properties.adm1_en]??"Explore this region and discover its provinces, cities, municipalities and communities."}</motion.p><motion.div className="detailGrid" initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} transition={{delay:.15,duration:.3,ease}}><div><strong>Region</strong><small>Administrative level</small></div><div><strong>PSGC</strong><small>Geographic code</small></div></motion.div></motion.aside>:<motion.aside key="welcome" className="panel" initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} transition={{delay:.5,duration:.45,ease}}><div className="panelTop"><span>18 REGIONS</span><MapPin size={16}/></div><h2>The islands, at a glance.</h2><p>Start anywhere. The map is the navigation. Select a region or use search to jump directly to one.</p></motion.aside>}</AnimatePresence>
   </div></div></section>
  <motion.footer className="footer" initial={{opacity:0}} whileInView={{opacity:1}} viewport={{once:true,amount:.5}} transition={{duration:.5}}><span>Philippine interactive map</span><span>Original UI · open geographic boundary data</span></motion.footer>
 </div>
}