'use client';
import {useEffect,useMemo,useState} from "react";
import {geoMercator,geoPath,type GeoGeometryObjects} from "d3-geo";
import {AnimatePresence,motion} from "framer-motion";
import {ArrowLeft,Search,MapPin} from "lucide-react";
type F={type:"Feature";geometry:GeoGeometryObjects;properties:{adm1_psgc:number;adm1_en:string}};
type C={type:"FeatureCollection";features:F[]};
const URL="https://raw.githubusercontent.com/tordecilla/ph-drilldown-map/main/geo-nir/country.0.001.json";
const desc:Record<string,string>={"National Capital Region (NCR)":"The country's metropolitan capital and a center of government, commerce and culture.","Cordillera Administrative Region (CAR)":"A mountainous northern Luzon region known for highland communities and terraces.","Region I (Ilocos Region)":"Northern Luzon, known for heritage towns, coastlines and mountain landscapes.","Region II (Cagayan Valley)":"A wide northern valley framed by the Sierra Madre and Cordillera ranges.","Region III (Central Luzon)":"A broad plain at the heart of Luzon and a major agricultural region.","Region IV-A (CALABARZON)":"A highly connected region south of Metro Manila with cities, industry and countryside.","MIMAROPA Region":"An archipelagic region of islands, reefs, forests and coastal communities.","Region V (Bicol Region)":"The Bicol peninsula and its islands, shaped by volcanoes and the Pacific.","Region VI (Western Visayas)":"Panay, Guimaras and surrounding island communities.","Negros Island Region (NIR)":"Negros and Siquijor, a central island region of diverse communities.","Region VII (Central Visayas)":"A central island corridor anchored by Cebu and Bohol.","Region VIII (Eastern Visayas)":"The eastern seaboard of the Visayas facing the Pacific.","Region IX (Zamboanga Peninsula)":"The western peninsula of Mindanao, rich in coastal and cultural diversity.","Region X (Northern Mindanao)":"Northern Mindanao's highlands, cities and coastal plains.","Region XI (Davao Region)":"Southeastern Mindanao centered around Davao and Mount Apo.","Region XII (SOCCSKSARGEN)":"A diverse south-central Mindanao region of coasts, plains and highlands.","Region XIII (Caraga)":"Northeastern Mindanao, known for forests, rivers and Pacific coastlines.","Bangsamoro Autonomous Region In Muslim Mindanao (BARMM)":"An autonomous region spanning parts of mainland Mindanao and the Sulu archipelago."};
const short=(s:string)=>s.replace(/^Region \d+\s*\((.*)\)$/,"$1").replace(/^Region \w+\s*/,"").trim();
export default function PhilippinesMap(){const[data,setData]=useState<C|null>(null);const[selected,setSelected]=useState<F|null>(null);const[q,setQ]=useState("");
useEffect(()=>{fetch(URL).then(r=>r.json()).then(setData).catch(()=>{})},[]);
const fs=data?.features??[];const filtered=useMemo(()=>fs.filter(f=>f.properties.adm1_en.toLowerCase().includes(q.toLowerCase())),[fs,q]);
const projection=useMemo(()=>data?geoMercator().fitExtent([[35,15],[965,565]],data as any):geoMercator(),[data]);const path=useMemo(()=>geoPath(projection),[projection]);
return <div className="site"><header className="header"><div className="wordmark">THE PHILIPPINES</div><a className="source" href="https://github.com/tordecilla/ph-drilldown-map" target="_blank">MAP DATA ↗</a></header>
<motion.section className="hero" initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} transition={{duration:.45}}><div className="eyebrow">An interactive map</div><h1>Explore the Philippines.</h1><p>One country, eighteen regions, thousands of places. Select a region to begin your way through the islands.</p></motion.section>
<section className="mapSection"><div className="mapFrame"><div className="mapMeta"><b>REGIONS</b><span>Tap or hover a region</span></div><div className="mapWrap"><div className="search"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Find a region…"/>{q&&<div className="searchResults">{filtered.map(f=><button className="result" key={f.properties.adm1_psgc} onClick={()=>{setSelected(f);setQ("")}}>{short(f.properties.adm1_en)}<small>{f.properties.adm1_psgc}</small></button>)}</div>}</div>
<svg className="mapSvg" viewBox="0 0 1000 600" aria-label="Interactive Philippine regional map">{data?fs.map((f,i)=><motion.path key={f.properties.adm1_psgc} d={path(f as any)||""} className={"regionPath "+(selected?.properties.adm1_psgc===f.properties.adm1_psgc?"active ":"")+(selected&&selected.properties.adm1_psgc!==f.properties.adm1_psgc?"dim":"")} initial={{opacity:0}} animate={{opacity:selected&&selected.properties.adm1_psgc!==f.properties.adm1_psgc?.35:1}} transition={{duration:.28,delay:Math.min(i*.015,.25)}} onClick={()=>setSelected(f)} tabIndex={0} onKeyDown={e=>e.key==="Enter"&&setSelected(f)}/>):<text x="500" y="300" textAnchor="middle" fill="#68717c">Loading the map…</text>}</svg>
<AnimatePresence>{selected?<motion.aside className="panel" initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} exit={{opacity:0,y:12}}><div className="panelTop"><button className="back" onClick={()=>setSelected(null)}><ArrowLeft size={14}/> All regions</button><span>{selected.properties.adm1_psgc}</span></div><h2>{short(selected.properties.adm1_en)}</h2><p>{desc[selected.properties.adm1_en]??"Explore this region and discover its provinces, cities, municipalities and communities."}</p><div className="detailGrid"><div><strong>Region</strong><small>Administrative level</small></div><div><strong>PSGC</strong><small>Geographic code</small></div></div></motion.aside>:<motion.aside className="panel" initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} transition={{delay:.35}}><div className="panelTop"><span>18 REGIONS</span><MapPin size={16}/></div><h2>The islands, at a glance.</h2><p>Start anywhere. The map is the navigation. Select a region or use search to jump directly to one.</p></motion.aside>}</AnimatePresence></div></div></section>
<footer className="footer"><span>Philippine interactive map</span><span>Original UI · open geographic boundary data</span></footer></div>}